pointcloud_to_laserscan_node:
  ros__parameters:
    transform_tolerance: 0.01
    min_height: -1000.0
    max_height: 2000.0
    angle_min: -1.5708  # -M_PI/2
    angle_max: 1.5708   # M_PI/2
    angle_increment: 0.003
    scan_time: 0.1
    range_min: 0.0
    range_max: 10.0
    use_inf: true
    inf_epsilon: 1.0
